[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = '0.8.23'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
